name: Build

on: [ push, pull_request ]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install boost
        uses: MarkusJx/install-boost@v2.4.4
        id: install-boost
        with:
            boost_version: 1.83.0
            platform_version: 12
            toolset: clang
      - name: Configure library
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_OSX_DEPLOYMENT_TARGET=10.5 -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64"
        env:
          BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}
      - name: Build library
        run: cmake --build build --config Release -j $(sysctl -n hw.logicalcpu)
      - name: Run tests
        working-directory: build/test
        run: ctest
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Examples
          path: build/examples/*.app
